# Generated by Django 4.1.5 on 2023-01-27 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_transaction_file_upload"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="file_upload",
        ),
    ]
