# Generated by Django 4.1.5 on 2023-01-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0003_remove_transaction_file_upload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="card",
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="hour",
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="shop_name",
            field=models.CharField(max_length=19),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="shop_owner",
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="value",
            field=models.CharField(max_length=10),
        ),
    ]
