# Generated by Django 4.1.5 on 2023-01-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0005_alter_transaction_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="hour",
            field=models.CharField(max_length=10),
        ),
    ]
